### ISSUE TITLE
Boot error on NanoPi R4S 1G

### ISSUE THREAD

**Issue by xfarre** [quintus-lab/openwrt-rockchip#33]
Hello!

I am trying to use you master image in my NanoPi R4S 1G and it doesn't boot. 
In Serial Console I get this message:

`U-Boot TPL 2021.07 (Aug 16 2021 - 19:37:33)
sdram_init: LPDDR4 - 50MHz failed!
rk3399_dmc_init DRAM init failed -22
Missing DTB
`

It looks like it is looking for a LPDDR4 (installed in NanoPi R4S **4Gb** version) but 1Gb has DDR3 memory.

There is any way to change inside SD card or kernel must be recompiled?

Thanks in advance.
Best Regards XF.-

**Comment by quintus-lab** [comment]
I think that is a problem with uboot rockchip version 2021.07, it's gonna take some time to fix that.
pls try use the old version before a mouth ago.

**Comment by mikegleasonjr** [comment]
Hi everyone, I have the same issue, my 1G R4S is not booting the current official OpenWRT release: https://downloads.openwrt.org/releases/22.03.0-rc4/targets/rockchip/armv8/openwrt-22.03.0-rc4-rockchip-armv8-friendlyarm_nanopi-r4s-ext4-sysupgrade.img.gz

FriendlyWRT works.

How can I take the latest release from OpenWRT and make it boot on my Nanopi r4s ? The FriendlyWRT version is like 1 gigabytes and full of bloat.

Thanks

**Comment by mikegleasonjr** [comment]
Ok after reading the main page of OpenWRT, they are suggesting a couple of git builds because the y state they don't support the 1G version yet (https://openwrt.org/toh/friendlyarm/nanopi_r4s_v1).

I was able to get a recent build from here for anyone encountering this thread: https://github.com/anaelorlinski/OpenWrt-NanoPi-R2S-R4S-Builds

Thanks everyone for the efforts to have the R4S running on OpenWRT.
